import { renderConfigured } from '../../templates/infrastructure/snapshot.js';
import { randomUUID } from 'node:crypto';
import type { Database } from '../../../infrastructure/prisma/database.js';
import { AppError, type Actor, type Role } from '../../../application/context.js';
import { verifyMembership, DEFAULT_PRACTICE, scoped, type Tx } from './scope.js';
import { branding, type Branding } from '../application/settings.js';
import { defaultTemplate, validateTemplate, populate, type TemplateDefinition } from '../../templates/application/template.js';
import { plans, effectiveState, simulatedSubscription } from '../../subscription/application/policy.js';
const json=(v:unknown)=>JSON.parse(JSON.stringify(v));
const admin=(a:Actor)=>{if(a.role!=='ADMINISTRATOR'&&!a.canManage)throw new AppError('FORBIDDEN','Practice administrator permission required.');};
export function practiceServices(db:Database) {
 async function transaction<T>(actor:Actor|null,action:string,run:(tx:Tx,practiceId:string,a:Actor)=>Promise<T>){if(!actor)throw new AppError('UNAUTHENTICATED','Sign in first.');return db.$transaction(async tx=>{const id=actor.practiceId??DEFAULT_PRACTICE;await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtextextended(${id}, 0))::text`;await verifyMembership(tx,actor);const result=await run(tx,id,actor);await tx.auditEvent.create({data:{practiceId:id,actorId:actor.id,action,subjectId:id,outcome:'SUCCESS',correlationId:randomUUID()}});return result;});}
 return {
 async actor(actor:Actor|null,requested:string|null){if(!actor)return null;const m=requested?await db.membership.findFirst({where:{practiceId:requested,userId:actor.id,active:true}}):await db.membership.findFirst({where:{userId:actor.id,active:true},orderBy:{practiceId:'asc'}});return m?{...actor,practiceId:m.practiceId,role:m.role as Role,canManage:m.canManage}:null;},
 async list(actor:Actor|null){if(!actor)throw new AppError('UNAUTHENTICATED','Sign in first.');const memberships=await db.membership.findMany({where:{userId:actor.id,active:true}});const practices=await db.practice.findMany({where:{id:{in:memberships.map(m=>m.practiceId)}}});return practices.map(p=>({...p,role:memberships.find(m=>m.practiceId===p.id)!.role}));},
 async create(actor:Actor|null,name:string){if(!actor)throw new AppError('UNAUTHENTICATED','Sign in first.');if(!name.trim()||name.length>100)throw new AppError('VALIDATION','Practice name is required (max 100 characters).');return transaction(actor,'practice.create',async(tx,_id,a)=>{const p=await tx.practice.create({data:{name}});await tx.membership.create({data:{practiceId:p.id,userId:a.id,role:a.role==='CLINICIAN'?'CLINICIAN':'ADMINISTRATOR',canManage:true}});await tx.practiceSubscription.create({data:{practiceId:p.id,...simulatedSubscription('SOLO','TRIAL')}});return p;});},
 settings(actor:Actor|null){return transaction(actor,'practice.settings',async(tx,id,a)=>{const p=await tx.practice.findUniqueOrThrow({where:{id}});const sub=await tx.practiceSubscription.findUniqueOrThrow({where:{practiceId:id}});return {...p,subscription:{...sub,effectiveState:effectiveState(sub),seatLimit:plans[sub.plan as keyof typeof plans]},members:(a.role==='ADMINISTRATOR'||a.canManage)?await tx.membership.findMany({where:{practiceId:id},include:{user:{select:{username:true,name:true}}}}):[]};});},
 member(actor:Actor|null,input:{username:string;role:string;active:boolean;expected:number}){return transaction(actor,'practice.membership',async(tx,id,a)=>{admin(a);if(!['CLINICIAN','RECEPTION','ADMINISTRATOR'].includes(input.role))throw new AppError('VALIDATION','Invalid membership role.');const user=await tx.user.findUnique({where:{username:input.username}});if(!user||!user.active)throw new AppError('NOT_FOUND','Existing active synthetic account required.');const prior=await tx.membership.findUnique({where:{practiceId_userId:{practiceId:id,userId:user.id}}});if((prior?.version??0)!==input.expected)throw new AppError('CONFLICT','Membership changed. Reload.');if(prior&&(prior.role==='ADMINISTRATOR'||prior.canManage)&&prior.active&&(!input.active||(!prior.canManage&&input.role!=='ADMINISTRATOR'))&&await tx.membership.count({where:{practiceId:id,active:true,OR:[{role:'ADMINISTRATOR'},{canManage:true}]}})<=1)throw new AppError('VALIDATION','Keep at least one active administrator.');const sub=await tx.practiceSubscription.findUniqueOrThrow({where:{practiceId:id}});if(input.active&&input.role==='CLINICIAN'&&!(prior?.active&&prior.role==='CLINICIAN')&&await tx.membership.count({where:{practiceId:id,active:true,role:'CLINICIAN'}})>=plans[sub.plan as keyof typeof plans])throw new AppError('VALIDATION','Clinician seat limit reached.');return tx.membership.upsert({where:{practiceId_userId:{practiceId:id,userId:user.id}},create:{practiceId:id,userId:user.id,role:input.role,active:input.active},update:{role:input.role,active:input.active,version:{increment:1}}});});},
 brand(actor:Actor|null,expected:number,value:Branding){branding(value);return transaction(actor,'practice.branding',async(tx,id,a)=>{admin(a);const r=await tx.practice.updateMany({where:{id,version:expected},data:{branding:json(value),name:value.systemName,version:{increment:1}}});if(!r.count)throw new AppError('CONFLICT','Branding changed. Reload.');return tx.practice.findUniqueOrThrow({where:{id}});});},
 templates(actor:Actor|null){return transaction(actor,'template.list',async(tx,id,a)=>{admin(a);return tx.documentTemplate.findMany({where:{practiceId:id}});});},
 saveTemplate(actor:Actor|null,kind:string,expected:number,value:TemplateDefinition,publish:boolean){validateTemplate(value);if(!['PRESCRIPTION','CERTIFICATE'].includes(kind))throw new AppError('VALIDATION','Invalid document kind.');return transaction(actor,'template.save',async(tx,id,a)=>{admin(a);const prior=await tx.documentTemplate.findUnique({where:{practiceId_kind:{practiceId:id,kind}}});if((prior?.version??0)!==expected)throw new AppError('CONFLICT','Template changed. Reload.');const version=expected+1;const t=await tx.documentTemplate.upsert({where:{practiceId_kind:{practiceId:id,kind}},create:{practiceId:id,kind,definition:json(value),version,publishedVersion:publish?version:null},update:{definition:json(value),version,...(publish?{publishedVersion:version}:{})}});if(publish)await tx.templateRevision.create({data:{practiceId:id,templateId:t.id,version,definition:json(value),authorId:a.id}});return t;});},
 previewTemplate(actor:Actor|null,value:TemplateDefinition,kind:string='CERTIFICATE'){validateTemplate(value);return transaction(actor,'template.preview',async(tx,id,a)=>{admin(a);if(!['PRESCRIPTION','CERTIFICATE'].includes(kind))throw new AppError('VALIDATION','Invalid document kind.');const practice=await tx.practice.findUniqueOrThrow({where:{id}});const brand=practice.branding as Record<string,string>;const values={'patient.fullName':'Demo Patient','patient.birthDate':'1990-01-01','patient.ageAtIssue':'36','patient.address':'Synthetic address','clinic.name':'Demo Clinic','clinic.address':'Synthetic clinic address','clinic.phone':'000000','clinic.email':'demo@example.test','doctor.fullName':'Dr Demo','document.issueDate':'2026-09-11'};for(const section of [value.heading,value.body,value.footer])populate(section,values);return renderConfigured(kind as 'PRESCRIPTION'|'CERTIFICATE',{id:'preview',documentId:'synthetic-preview',version:1,state:'ISSUED',content:kind==='PRESCRIPTION'?{items:[{medication:'Demo medication',strength:'Demo strength',dose:'Demo dose',route:'Demo route',frequency:'Demo frequency',duration:'Demo duration',quantity:'Demo quantity',repeats:0}],directions:'Synthetic directions only.'}:{title:'Demo medical certificate',statement:'Synthetic certificate statement.',startsOn:'2026-09-11',endsOn:'2026-09-12'},patientSnapshot:{id:'synthetic-patient',name:'Demo Patient',birthDate:'1990-01-01'},issuerSnapshot:{id:'synthetic-clinician',name:'Dr Demo'},templateVersion:'synthetic-preview',authorId:'synthetic-clinician',reason:'',previousVersion:null,recordedAt:'2026-09-11T00:00:00Z'},value,brand,{...values,'clinic.name':brand.systemName||practice.name});});},
 subscription(actor:Actor|null,expected:number,plan:string,state:string){const chosen=simulatedSubscription(plan,state);return transaction(actor,'subscription.simulated',async(tx,id,a)=>{admin(a);if(await tx.membership.count({where:{practiceId:id,active:true,role:'CLINICIAN'}})>plans[plan as keyof typeof plans])throw new AppError('VALIDATION','Plan cannot contain current clinician seats.');const r=await tx.practiceSubscription.updateMany({where:{practiceId:id,version:expected},data:{...chosen,version:{increment:1}}});if(!r.count)throw new AppError('CONFLICT','Subscription changed. Reload.');return tx.practiceSubscription.findUniqueOrThrow({where:{practiceId:id}});});},
 export(actor:Actor|null){return transaction(actor,'practice.export',async(raw,id,a)=>{const tx=scoped(raw,id);return {practiceId:id,patients:await tx.patient.findMany(),appointments:await tx.appointment.findMany(),...(a.role==='CLINICIAN'?{consultations:await tx.consultation.findMany(),notes:await tx.noteRevision.findMany(),documents:await tx.clinicalDocument.findMany(),documentRevisions:await tx.documentRevision.findMany()}:{}),...(a.role==='ADMINISTRATOR'?{audit:await tx.auditEvent.findMany(),practice:await raw.practice.findUnique({where:{id}}),templates:await tx.documentTemplate.findMany()}: {})};});},
 };
}
export { defaultTemplate };
