import { expect, test, type Page } from '@playwright/test';
const password='Synthetic-browser-2026';
async function login(page:Page,user:string){await page.goto('/clinic');await page.getByLabel('Username',{exact:true}).fill(user);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Sign out',exact:true})).toBeVisible();}
async function selectPatient(page:Page,name:string){await page.getByLabel('Search patients',{exact:true}).fill(name);await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('button',{name:`${name} Demo`,exact:true}).click();}
test('reception and clinician complete persistent patient, clinical, print and scheduling workflows',async({page})=>{
 await login(page,'reception');
 await page.getByRole('button',{name:'Register patient',exact:true}).click();
 await page.getByLabel('Given name',{exact:true}).fill('Browser');await page.getByLabel('Family name',{exact:true}).fill('Demo');await page.getByLabel('Birth date (YYYY-MM-DD)',{exact:true}).fill('1991-02-03');await page.getByLabel('Phone',{exact:true}).fill('0400111222');await page.getByRole('button',{name:'Save patient',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Browser Demo',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Consultations',exact:true})).toHaveCount(0);
 await page.getByLabel('Phone',{exact:true}).fill('0400333444');await page.getByRole('button',{name:'Save patient',exact:true}).click();await expect(page.getByText(/Profile version 2/)).toBeVisible();
 await page.getByRole('button',{name:'Appointments',exact:true}).last().click();await page.getByLabel('Appointment start (local)',{exact:true}).fill('2027-03-01T09:00');await page.getByLabel('Appointment end (local)',{exact:true}).fill('2027-03-01T09:30');await page.getByRole('button',{name:'Book appointment',exact:true}).click();
 await expect(page.getByRole('button',{name:'Reschedule appointment',exact:true})).toBeVisible();await page.getByRole('button',{name:'Reschedule appointment',exact:true}).click();await page.getByLabel('Reschedule start (local)',{exact:true}).fill('2027-03-01T10:00');await page.getByLabel('Reschedule end (local)',{exact:true}).fill('2027-03-01T10:30');await page.getByRole('button',{name:'Save reschedule',exact:true}).click();
 await page.getByRole('button',{name:'Check in patient',exact:true}).click();await page.getByRole('button',{name:'Confirm patient identity',exact:true}).click();await page.getByRole('button',{name:'Record arrival',exact:true}).click();await expect(page.getByText('CHECKED_IN · version 3',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await login(page,'clinician');await selectPatient(page,'Browser');
 await page.getByRole('button',{name:'Consultations',exact:true}).click();await page.getByRole('button',{name:'Start consultation',exact:true}).click();await page.getByLabel('Consultation note',{exact:true}).fill('Synthetic browser note.');await page.getByRole('button',{name:'Finalize note',exact:true}).click();
 await expect(page.getByText('OPEN · note FINALIZED v1',{exact:true})).toBeVisible();await page.getByLabel('Consultation note',{exact:true}).fill('Amended synthetic browser note.');await page.getByLabel('Note amendment reason',{exact:true}).fill('Corrected synthetic detail');await page.getByRole('button',{name:'Save note amendment',exact:true}).click();await expect(page.getByText('OPEN · note FINALIZED v2',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Note version history',exact:true}).click();await expect(page.getByText('Synthetic browser note.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Documents',exact:true}).click();await page.getByRole('button',{name:'New prescription',exact:true}).click();
 for(const [field,value] of Object.entries({Medication:'Demo medication',Strength:'10 mg',Dose:'One tablet',Route:'Oral',Frequency:'Daily',Duration:'Five days',Quantity:'Five'}))await page.getByLabel(`${field} 1`,{exact:true}).fill(value);
 await page.getByLabel('Prescription directions',{exact:true}).fill('Synthetic directions only.');await page.getByRole('button',{name:'Create document draft',exact:true}).click();await page.getByRole('button',{name:'Edit prescription v1',exact:true}).click();await page.getByRole('button',{name:'Issue demo document',exact:true}).click();await page.getByRole('button',{name:'Preview prescription v2',exact:true}).click();
 const frame=page.frameLocator('iframe[title="Clinical document preview"]');await expect(frame.getByText('DEMO — NOT FOR CLINICAL USE',{exact:true})).toBeVisible();await expect(frame.getByText('Synthetic directions only.',{exact:true})).toBeVisible();
 // Exercise the browser print adapter without opening an interactive OS dialog in CI.
 await page.locator('iframe').evaluate((iframe:HTMLIFrameElement)=>{if(iframe.contentWindow)iframe.contentWindow.print=()=>{};});await page.getByRole('button',{name:'Print / Save PDF',exact:true}).click();await page.getByRole('button',{name:'Cancel preview',exact:true}).click();
 await page.getByRole('button',{name:'New certificate',exact:true}).click();await page.getByLabel('Certificate statement',{exact:true}).fill('This is a synthetic certificate statement.');await page.getByRole('button',{name:'Create document draft',exact:true}).click();await page.getByRole('button',{name:'Edit certificate v1',exact:true}).click();await page.getByRole('button',{name:'Issue demo document',exact:true}).click();await page.getByRole('button',{name:'Preview certificate v2',exact:true}).click();await expect(frame.getByText('This is a synthetic certificate statement.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Cancel preview',exact:true}).click();
 await page.getByRole('button',{name:'History',exact:true}).click();await expect(page.getByText('Synthetic browser note.',{exact:true})).toBeVisible();await expect(page.getByText('Amended synthetic browser note.',{exact:true})).toBeVisible();
 await page.reload();await selectPatient(page,'Browser');await expect(page.getByLabel('Phone',{exact:true})).toHaveValue('0400333444');
 await page.screenshot({path:'test-results/mvp/clinical-workspace.png',fullPage:true});
});
test('administrator sees audit metadata and has no clinical tabs',async({page})=>{await login(page,'admin');await selectPatient(page,'Browser');await expect(page.getByRole('button',{name:'Documents',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Audit',exact:true}).click();await expect(page.getByRole('heading',{name:'Audit trail',exact:true})).toBeVisible();await expect(page.getByText(/document.print/).first()).toBeVisible();});
